apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.0.8
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: "/data/db"
              name: my-mongo-volume
        - name: redis
          image: redis:6
        - name: web
          image: rosered/node-redis
      volumes:
        - name: my-mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc